apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
spec:
  license:
    accept: true
    license: Enterprise
  fileStorageClass: ocs-storagecluster-cephfs
  blockStorageClass: ocs-storagecluster-ceph-rbd
  version: 4.5.0
